{
  "openapi": "3.0.1",
  "info": {
    "version": "0.0.1",
    "title": "API Drink-Master",
    "description": "API for project App Drink-Master",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json", "multipart/form-data"],
  "produces": ["application/json"],
  "servers": [
    { "url": "http://localhost:3000" },
    { "url": "https://rest-api-drink-master.onrender.com" }
  ],

  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Users",
      "description": "Users endpoints"
    },
    {
      "name": "Filters",
      "description": "Filters endpoints"
    },
    {
      "name": "Drinks",
      "description": "Drinks endpoints"
    }
  ],
  "paths": {
    "/api/auth/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists (Email in use)",
            "content": {}
          }
        }
      }
    },
    "/api/auth/signin": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "parameters": [],
        "requestBody": {
          "description": "Login data object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation of login",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Email, password is wrong or not verify.",
            "content": {}
          }
        }
      }
    },
    "/api/auth/signout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {},
        "responses": {
          "204": {
            "description": "Successful operation of logout",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LogoutResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/users/current": {
      "get": {
        "tags": ["Users"],
        "summary": "Get current User information",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetCurrentUserResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/users/update": {
      "patch": {
        "tags": ["Users"],
        "summary": "User profile update",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Date for update User profile",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UpdateProfileRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation of subscribe",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateProfileResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request ( File is required for this request)",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          },
          "404": {
            "description": "User not found",
            "content": {}
          }
        }
      }
    },
    "/api/users/subscribe": {
      "post": {
        "tags": ["Users"],
        "summary": "User subscription to e-mails",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "E-mail for subscription",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SubscribeRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation of subscribe",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SubscribeResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request ( Email is required)",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/api/drinks/mainpage": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Array of objects All recipes drinks",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "schema": { "type": "number" },
            "value": "1"
          },
          {
            "name": "limit",
            "in": "query",
            "schema": { "type": "number" },
            "value": "10"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recipesMainpageResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/drinks/byid/:recipeId": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Object of recipe drink",
        "parameters": [
          {
            "name": "id",
            "in": "params",
            "schema": { "type": "string" },
            "value": "639b6de9ff77d221f190c50f"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recipeResponse"
                }
              }
            }
          },
          "400": {
            "description": "For adult only",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/api/drinks/own": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Array of objects only User recipes drinks",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recipesMainpageResponse"
                }
              }
            }
          },
          "404": {
            "description": "User haven't recipes yet",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/drinks/own/add": {
      "post": {
        "tags": ["Drinks"],
        "summary": "Add User's recipe",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "User's recipe",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/recipeOwnRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation add recipe",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recipeOwnResponse"
                }
              }
            }
          },
          "400": {
            "description": "Provide all fields data",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/drinks/own/remove": {
      "delete": {
        "tags": ["Drinks"],
        "summary": "Remove User's recipe",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "User's recipe",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/recipeRemoveRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recipeResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/drinks/favorite": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Array of objects only User's favorite drinks",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recipesMainpageResponse"
                }
              }
            }
          },
          "404": {
            "description": "User haven't favorite recipes yet",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/drinks/favorite/add": {
      "post": {
        "tags": ["Drinks"],
        "summary": "Add User's favorite recipe",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "User's favorite recipe",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/recipeFavoriteRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recipeFavoriteResponse"
                }
              }
            }
          },
          "404": {
            "description": "Сocktail has already been added!",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },
    "/api/drinks/favorite/remove": {
      "delete": {
        "tags": ["Drinks"],
        "summary": "Remove User's favorite recipe",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "User's favorite recipe",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/recipeRemoveRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/recipeResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password", "name", "birthDate"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          },
          "name": {
            "type": "string",
            "description": "User's password",
            "example": "OurUser"
          },
          "birthDate": {
            "type": "number",
            "description": "Birth Data our users",
            "example": "1000924800"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password hash",
            "example": "qwe/A554rty1DDddgG23"
          },
          "name": {
            "type": "string",
            "description": "User's Name",
            "example": "OurUser"
          },
          "avatarURL": {
            "type": "string",
            "description": "URL from saved User's avatar",
            "example": "www.cloud.com/avatar/c73e3fb5ccb242540b08931"
          },
          "birthDate": {
            "type": "number",
            "description": "Birth Data our users",
            "example": "1000924800"
          },
          "adult": {
            "type": "boolean",
            "description": "Our User adult or not adult",
            "example": false
          }
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "User's session's token",
            "example": "Ouzzfdf6545464FFFFser"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "adult": {
            "type": "boolean",
            "description": "Our User adult or not adult",
            "example": false
          }
        }
      },
      "LogoutResponse": {
        "type": "object",
        "properties": {}
      },
      "GetCurrentUserResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "name": {
            "type": "string",
            "description": "User's Name",
            "example": "UserName"
          }
        }
      },
      "SubscribeRequest": {
        "type": "object",
        "required": ["email"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          }
        }
      },
      "SubscribeResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's e-mail for which subscribed ",
            "format": "email"
          }
        }
      },
      "UpdateProfileRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's Name"
          },
          "avatar": {
            "type": "string",
            "format": "binary",
            "description": "User's avatar file"
          }
        }
      },
      "UpdateProfileResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "string" },
          "code": { "type": "number" },
          "data": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "avatarURL": { "type": "string" }
            }
          }
        }
      },

      "recipesMainpageResponse": {
        "type": "object",
        "properties": {
          "data" : {
            "type" : "array",
            "items": {
              "type": "object",
              "properties": {
                "drink": {
                  "type": "string",
                  "description": "Name of drink"
                },
                "drinkAlternate": {
                  "type": "string",
                  "description": "Alternative name drink"
                }
              }
            }
          }
        },
        "example": [
          {
            "favorites": [],
            "_id": "639b6de9ff77d221f190c55b",
            "drink": "Jitterbug",
            "drinkAlternate": "Sorry, not specified",
            "tags": "Sorry, not specified",
            "video": "Sorry, not specified",
            "category": "Cocktail",
            "IBA": "Sorry, not specified",
            "alcoholic": "Alcoholic",
            "glass": "Cocktail Glass",
            "description": "Jitterbug is a lively and energetic cocktail that will put a spring in your step. This invigorating drink combines the smoothness of vodka with the rich flavors of coffee liqueur and creamy Irish cream. The result is a delightful blend of coffee and cream with a subtle kick of vodka. Sip on a Jitterbug and let its lively flavors and creamy texture awaken your senses and keep you dancing all night long.",
            "instructions": "Wet glass, dip rim in sugar. Then add Ice. Then add everything else. It's that simple!",
            "instructionsES": "Vaso húmedo, borde de inmersión en azúcar. Luego agregue hielo. Luego agrega todo lo demás. ¡Es así de simple!",
            "instructionsDE": "Feuchtes Glas, Tauchrand in Zucker. Dann fügen Sie Eis hinzu. Dann füge alles andere hinzu. So einfach ist das!",
            "instructionsFR": "Mouiller le verre, tremper le bord dans le sucre. Ajoutez ensuite de la glace. Ajoutez ensuite tout le reste. C'est si simple!",
            "instructionsIT": "Bagna il biicchiere, immergere il bordo nello zucchero.\r\nQuindi aggiungi ghiaccio.\r\nQuindi aggiungi tutto il resto.\r\nÈ così semplice!",
            "instructionsRU": "Намочите стакан, окуните край в сахар. Затем добавьте лед. Затем добавьте все остальное. Это так просто!",
            "instructionsPL": "Mokre szkło, zanurz w cukrze. Następnie dodaj lód. Następnie dodaj wszystko inne. To takie proste!",
            "instructionsUK": "Намочити скло, занурити його обідок у цукор. Потім додайте лід. Потім додайте все інше. Це так просто!",
            "drinkThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689167155/cocktails-v1/drinks/Jitterbug.jpg",
            "ingredients": [
                {
                    "title": "Gin",
                    "measure": "2 jiggers ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4a6"
                },
                {
                    "title": "Vodka",
                    "measure": "1 jigger ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4b9"
                },
                {
                    "title": "Grenadine",
                    "measure": "3 dashes ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4c7"
                },
                {
                    "title": "Lime juice",
                    "measure": "1 shot ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4c1"
                },
                {
                    "title": "Sugar",
                    "measure": "Around rim put 1 pinch ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4bc"
                },
                {
                    "title": "Sugar syrup",
                    "measure": "3 dashes ",
                    "ingredientId": "64aebb7f82d96cc69e0eb4d4"
                },
                {
                    "title": "Soda water",
                    "measure": "Fill to top with ",
                    "ingredientId": "64f1d5d669d8333cf130fccd"
                }
            ],
            "shortDescription": "A lively and energetic cocktail with a blend of vodka, coffee liqueur, and creamy Irish cream."
        }
        ]
      },
      "recipeOwnRequest": {
        "type": "object",
          "properties": {
            "drink": {
              "type": "string",
              "description": "Name of drink"
            },
            "tags": {
              "type": "string",
              "description": "Alternative name drink"
            },
            "category": {
              "type": "string",
              "description": "category coctail"
            },
            "alcoholic": {
              "type": "string",
              "description": "type coctail, alcoholic or non-alcoholic"
            },
            "glass": {
              "type": "string",
              "description": "type glass"
            },
            "description": {
              "type": "string",
              "description": "Description coctail"
            },
            "instructions": {
              "type": "string",
              "description": "Instructions for make coctail"
            },
            "instructionsUK": {
              "type": "string",
              "description": "Instructions for make coctail on Ukrainian language"
            },
            "drinkThumb": {
              "type": "string",
              "format": "binary",
              "description": "User's coctail photo file"
            },
            "ingredients": {
              "type" : "array",
              "items": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "description": "Name of ingredient"
                  },
                  "measure": {
                    "type": "string",
                    "description": "Volume of ingredient"
                  },
                  "ingredientId": {
                    "type": "string",
                    "description": "ingredient id"
                  }
                }
              }
            },
            "shortDescription": {
              "type": "string",
              "description": "Short coctail description"
            }
          },
        "example": 
        {
          "drink" : "My drink1",
          "tags": "super drink, alcoholic",
          "category" : "super drink",
          "alcoholic": "Alcoholic",
          "glass":"tank",
          "description": "seas of gorilka",
          "instructions": "seas of gorilka",
          "instructionsUK": "seas of gorilka",
          "drinkThumb": "link to pictures",
          "ingredients": [{"title": "whisky",
                          "measure": "10 oz.",
                          "ingredientId": "64aebb7f82d96cc69e0eb4fa"}],
          "shortDescription": "seas of whisky"
      }
      },
      "recipeOwnResponse": {
        "type": "object",
        "properties": {
          "drink": {
            "type": "string",
            "description": "Name of drink"
          },
          "tags": {
            "type": "string",
            "description": "Alternative name drink"
          },
          "category": {
            "type": "string",
            "description": "category coctail"
          },
          "alcoholic": {
            "type": "string",
            "description": "type coctail, alcoholic or non-alcoholic"
          },
          "glass": {
            "type": "string",
            "description": "type glass"
          },
          "description": {
            "type": "string",
            "description": "Description coctail"
          },
          "instructions": {
            "type": "string",
            "description": "Instructions for make coctail"
          },
          "instructionsUK": {
            "type": "string",
            "description": "Instructions for make coctail on Ukrainian language"
          },
          "drinkThumb": {
            "type": "string",
            "format": "binary",
            "description": "User's coctail photo file"
          },
          "ingredients": {
            "type" : "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "Name of ingredient"
                },
                "measure": {
                  "type": "string",
                  "description": "Volume of ingredient"
                },
                "ingredientId": {
                  "type": "string",
                  "description": "ingredient id"
                }
              }
            }
          },
          "shortDescription": {
            "type": "string",
            "description": "Short coctail description"
          },
          "favorites": {
            "type" : "array",
            "items": {
              "description": "Users id, who added this coctails to Favorite pages",
              "type": "string",
              "Example": "650c80426c3c09abd848e590"
            }
          },
          "owner": {
            "type": "string",
            "description": "User id, who is created this recipe",
            "Example": "650c80426c3c09abd848e590"
          }
        },

        "example": 
        {
          "code": 201,
          "message": "success",
          "data": {
              "drink": "My drink1",
              "tags": "super drink, alcoholic",
              "category": "super drink",
              "alcoholic": "Alcoholic",
              "glass": "tank",
              "description": "seas of gorilka",
              "instructions": "seas of gorilka",
              "instructionsUK": "seas of gorilka",
              "drinkThumb": "link to pictures",
              "ingredients": [
                  {
                      "title": "whisky",
                      "measure": "10 oz.",
                      "ingredientId": "64aebb7f82d96cc69e0eb4fa"
                  }
              ],
              "favorites": [],
              "shortDescription": "seas of whisky",
              "owner": "650c80426c3c09abd848e590",
              "_id": "650dbed4dfb6b4dd39c20bae",
              "createdAt": "2023-09-22T16:20:36.355Z",
              "updatedAt": "2023-09-22T16:20:36.355Z"
          }
      }
      },
      "recipeFavoriteRequest": {
        "type": "object",
        "required": ["id"],
          "properties": {
            "id": {
              "type": "string",
              "description": "Recipe id"
            }
          },
        "example": 
        { "id": "639b6de9ff77d221f190c50f" }
      },
      "recipeFavoriteResponse": {
        "type": "object",
          "properties": {
            "drink": {
              "type": "string",
              "description": "Name of drink"
            },
            "drinkAlternate": {
              "type": "string",
              "description": "Alternative name drink"
            }
          },
        "example": 
        {
          "code": 201,
          "message": "Success operation",
          "data": {
              "favorites": [
                  "650c80426c3c09abd848e590"
              ],
              "_id": "639b6de9ff77d221f190c51a",
              "drink": "ACID",
              "drinkAlternate": "Sorry, not specified",
              "tags": "Sorry, not specified",
              "video": "Sorry, not specified",
              "category": "Shot",
              "IBA": "Sorry, not specified",
              "alcoholic": "Alcoholic",
              "glass": "Shot glass",
              "description": "ACID is a bold and electrifying cocktail that will jolt your senses. This potent drink features a mix of high-proof spirits, such as rum and vodka, blended with a burst of citrus flavors. The result is a powerful and intense cocktail that packs a punch and delivers an electrifying experience. Approach ACID with caution and let its high-energy flavors ignite your palate.",
              "instructions": "Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.",
              "instructionsES": "Vierta primero el Bacardi 151, seguido del Wild Turkey 101 y sirva con Coca-Cola o Dr Pepper.",
              "instructionsDE": "Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.",
              "instructionsFR": "Pauvre dans le 151 premier suivi du 101 servi avec un chasseur Coke ou Dr Pepper.",
              "instructionsIT": "Versa prima il Bacardi 151 seguito dal 101, servito con una Coca-Cola.",
              "instructionsRU": "Плохо в 151 первом, за которым следует 101 подается с кока-колой или Dr Pepper Chaser.",
              "instructionsPL": "Biedny w 151, a następnie w 101 podawanych z pościgiem Coli lub Dr Pepper.",
              "instructionsUK": "Поганий у 151 першому, а потім у 101, який подається з кока-колою або др. перцем.",
              "drinkThumb": "http://res.cloudinary.com/dec1shvoo/image/upload/v1689167144/cocktails-v1/drinks/ACID.jpg",
              "ingredients": [
                  {
                      "title": "151 proof rum",
                      "measure": "1 oz Bacardi ",
                      "ingredientId": "64f1d5c269d8333cf130fb68"
                  },
                  {
                      "title": "Wild Turkey",
                      "measure": "1 oz ",
                      "ingredientId": "64f1d5de69d8333cf130fd56"
                  }
              ],
              "shortDescription": "A bold and electrifying cocktail with a mix of high-proof spirits and a burst of citrus.",
              "updatedAt": "2023-09-23T09:27:02.002Z"
          }
      }
      },
      "recipeRemoveRequest": {
        "type": "object",
        "required": ["id"],
          "properties": {
            "id": {
              "type": "string",
              "description": "Recipe id"
            }
          },
        "example": 
          { "id": "639b6de9ff77d221f190c50f" }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
